book/lib/book_web/router.ex
defmodule BookWeb.Router do
  use BookWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookWeb do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    resources "/book", BookController
    get "/", BookController, :index
    post "/book/:id", BookController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookWeb do
  #   pipe_through :api
  # end
end

book/lib/account/book.ex
defmodule Book.Account.Book do
  use Ecto.Schema
  import Ecto.Changeset
  alias Book.Account.LoanHistory
  

  schema "books" do
      field :code, :string
      field :title, :string
      field :author, :string
      has_many :loan_history,  LoanHistory
    timestamps()
  end

  @doc false
  def changeset(book, attrs) do
    book
    |> cast(attrs, [:code, :title, :author])
    |> validate_required([:code, :title, :author])
  end
end

book/lib/account/loan_history.ex
defmodule Book.Account.LoanHistory do
  use Ecto.Schema
  import Ecto.Changeset
  alias Book.Account.User
  alias Book.Account.Book
  
  schema "loans" do
    field :start_date, :date
    field :due_date, :date
    field :cost, :float
    field :status, :string
    field :extended, :integer
    belongs_to :user, User
    belongs_to :book, Book
    timestamps()
  end

  @doc false
  def changeset(loan_history, attrs) do
    loan_history
    |> cast(attrs, [:start_date, :due_date, :cost, :status, :extended, :user_id, :book_id])
    |> validate_required([[:start_date, :due_date, :cost, :status, :extended, :user_id, :book_id]])
  end
end

book/lib/account/user.ex
defmodule Book.Account.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Book.Account.LoanHistory
  

  schema "users" do
    field :username, :string
    has_many :loan_history, LoanHistory
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username])
    |> validate_required([:username])
  end
end

book/lib/book/application.ex
defmodule Book.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Book.Repo, []),
      # Start the endpoint when the application starts
      supervisor(BookWeb.Endpoint, []),
      # Start your own worker by calling: Book.Worker.start_link(arg1, arg2, arg3)
      # worker(Book.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Book.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    BookWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

book/lib/book/loan.ex
defmodule Book.Loan do

  import Ecto.Query, warn: false
  alias Book.Repo

  # alias Vueshatter.Models.LoanHistory
  alias Book.Account.Book
  alias Book.Account.User
  alias Book.Account.LoanHistory


  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end
 
  def create_books(attrs \\ %{}) do
    %Book{}
    |> Book.changeset(attrs)
    |> Repo.insert()
  end

  def create_loans(attrs \\ %{}) do
    %LoanHistory{}
    |> LoanHistory.changeset(attrs)
    |> Repo.insert()
  end

  def select_mybooks(accounts, my_id) do
    from l in accounts,
    join: b in Book,
    on: b.id == l.book_id,
    where: l.user_id == ^my_id,
    select: l
  end

  def get_my_books!(my_id) do
      from orders  in LoanHistory , where: orders.user_id == ^my_id
   end

  def my_books!(my_id, id), do: Repo.get_by(LoanHistory, user_id: my_id, book_id: id)

  def get_loan!(id), do: Repo.get!(LoanHistory, id)

  # def update_loan(%LoanHistory{} = loan, attrs) do
  #   loan
  #   |> LoanHistory.changeset(attrs)
  #   |> Repo.update()
  # end
end

book/lib/book/repo.ex
defmodule Book.Repo do
  use Ecto.Repo, otp_app: :book

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

book/lib/book_web/controllers/book_controller.ex
defmodule BookWeb.BookController do
  use BookWeb, :controller
  alias Book.{Repo, Accounts.Book, Loan, Accounts.LoanHistory, Accounts.User}


  def index(conn, _params) do
    books =  Loan.get_my_books!(1)|> Repo.all |> Repo.preload(:book)
    render(conn, "index.html", books: books)
  end
  
  def show(conn, %{"id" => id}) do
    result = Loan.get_loan!(id)
    # coder = Loan.get_my_books!(1)|> Repo.all |> Repo.preload(:book)
    if result.code == "A" do  
    extension = %{:due_date => Date.add(result.due_date, 7), :extended => result.extended+1}
    else 
    if  result.code == "B" do
      extension = %{:due_date => Date.add(result.due_date, 14), :extended => result.extended+1}
    else
      extension = %{:due_date => Date.add(result.due_date, 21), :extended => result.extended+1} 
    
    case (result.extended < 4) do
     true ->
      with {:ok, %LoanHistory{} = _loan} <- Loan.update_loan(result, extension) do
      conn |> put_flash(:info, "Extension accepted")
          |> redirect(to: "/")
      end
     false ->
      conn
       |> put_flash(:error, "Extension rejected")
       |> redirect(to: "/")
    end
  end
end
end
end

book/lib/book_web/controllers/page_controller.ex
defmodule BookWeb.PageController do
  use BookWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

book/lib/book_web/views/book_view.ex
defmodule BookWeb.BookView do
  use BookWeb, :view
end

book/lib/book_web/views/error_view.ex
defmodule BookWeb.ErrorView do
  use BookWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

book/lib/book_web/views/layout_view.ex
defmodule BookWeb.LayoutView do
  use BookWeb, :view
end

book/lib/book_web/views/page_view.ex
defmodule BookWeb.PageView do
  use BookWeb, :view
end

book/lib/book_web/templates/book/index.html.eex
<div id="index">
  {{message}}
</div>
<table class="table"> 
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Title</th>
      <th scope="col">Start Date</th>
      <th scope="col">Due Date</th>
      <th scope="col">Time extended</th>
      <th scope="col">Extend</th>
    </tr>
  </thead>
  <tbody> 
  <%= for loan <- @books do %>
  <tr>
    <td><%= @books.title  %></td>
    <td><%= @books.code  %></td>
    <td><%= loan.start_date %> </td>
    <td><%= loan.due_date %> </td>
    <td><%= lona.extended %> </td>
    <td class="text-right">
       <%= link "Extend", to: book_path(@conn, :show, loan.id), class: "btn-default"  %>
    </td> 
   </tr>  
<% end %>
  </tbody>
</table>
</div> 

book/lib/book_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Book!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

book/lib/book_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">Library <br />does not compromise speed and maintainability.</p>
</div>

<div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>